### ISSUE TITLE
ssl error: SSLCertVerificationError

### ISSUE THREAD

**Issue by skanthb** [Theamazingdp/AlteryxGalleryAPI#5]
Hi @Theamazingdp ,

I tried to run the below code and am facing an ssl error. Can you please guide me on where I'm making a mistake?

apiKey = 'xxxxxxxxxxxxxxxxxxxxxxxx'
apiSecret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
url = "https://name.corp.company.com:443/gallery/api/v1/workflows/subscription/"
httpMethod = 'GET'

params = {"oauth_consumer_key" : apiKey,
            "oauth_nonce" : str(math.floor(random()*1e9)),
            "oauth_signature_method" : "HMAC-SHA1",
            "oauth_timestamp" : str(int(math.floor(time()))),
            "oauth_version" : "1.0"}
sorted_params = collections.OrderedDict(sorted(params.items()))
normalized_params = urlencode(sorted_params)
q = lambda x: quote(x, safe="~")
base_string = "&".join((httpMethod.upper(), q(url), q(normalized_params)))

sig = hmac.new(bytes("&".join([apiSecret, '']), 'utf-8'), bytes(base_string, 'utf8'), hashlib.sha1)

signature = base64.b64encode(sig.digest()).decode().rstrip('\n')

params.update({'oauth_signature': signature})

requests.get(url, params=params)

error:
 File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Python37\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='name.corp.company.com', port=443): Max retries exceeded with url: /gallery/api/v1/workflows/subscription/?oauth_consumer_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx&oauth_nonce=677815294&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1552930371&oauth_version=1.0&oauth_signature=sOZGluTsWwwMbHfuvnfpi8gYUx0%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

can you please help?

Thanks,
Srikanth

**Comment by Theamazingdp** [comment]
Hey Srikanth,

Generally when I hit an SSL Cert error, it's due to something with the
server itself. Our current Alteryx Server is configured for SSL and has the
Https:// url, and we aren't seeing issues like the one you are sharing.
Have you verified that SSL is enabled on the server config? It looks like
you are using https in your url, so that would be my first check.
If not, it may just need to be http

Hope that helps.
